#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get install nginx -y
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo service nginx start
