#!/usr/bin/env bash
# config ngnix
config="
server {
        listen 80 default_server;

        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {

        try_files \$uri \$uri/ =404;

        }

        location /redirect_me {

        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;

        }
        
        error_page 404 /error_404.html;
        location = /error_404.html {
                root /var/www/html;
                internal;
        }
}
"
sudo apt-get update
sudo apt-get install nginx -y
sudo chmod 666 /var/www/html/index.nginx-debian.html /etc/nginx/sites-enabled/default /var/www/html/error_404.html
sudo chmod 644 /var/www/html/index.nginx-debian.html /etc/nginx/sites-e
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo -e "$config"> /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo chmod 644 /var/www/html/index.nginx-debian.html /etc/nginx/sites-enabled/default
sudo service nginx restart
