#!/bin/bash
echo 'Enter the add'
read
git add .

echo 'Enter the commit message:'
read commitMessage

git commit -m "$commitMessage"


git push 
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
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


