#!/usr/bin/env bash
# debugging web server nginx
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/ipv6only=on;/;/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
