#!/usr/bin/env bash
#displays numbers 1-20, bad luck in 4th , 9th , 17th
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    ((i++))
done