#!/usr/bin/env bash
#Gives information about a file
list=$(ls)
for file in $list
do
    if [[ $file == "school" ]]
    then
        echo "school file exists"
        if ! [[ -s $file ]]
        then
            echo "school file is empty"
        else
            echo "school file is not empty"
        fi
        if [[ -f $file ]]
        then
            echo "school is a regular file"
        fi
        i=1
        break
    fi
done
if [[ $i != 1 ]]
then
    echo "school file does not exist"
fi