#!/usr/bin/env bash
# configures an Ubuntu server to: localhost  to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts