#!/usr/bin/env bash
# run nginx with owner nginx
pkill nginx
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
